vich_uploader:
    db_driver: orm
    mappings:
        featured:
            uri_prefix: /images/blogs/featured
            upload_destination: '%kernel.project_dir%/public/images/blogs/featured'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        profile:
          uri_prefix: /images/users/profile
          upload_destination: '%kernel.project_dir%/public/images/users/profile'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer